version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    build: ./db
    environment:
      - POSTGRES_USER=vids_psg
      - POSTGRES_PASSWORD=vids_psg